// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWYr487z_VMAh_5KR3DDeq5S0ZNHXNGxo',
    appId: '1:660782661242:web:68f38472f75e50991085c3',
    messagingSenderId: '660782661242',
    projectId: 'task2-77e20',
    authDomain: 'task2-77e20.firebaseapp.com',
    storageBucket: 'task2-77e20.firebasestorage.app',
    measurementId: 'G-M67LC374JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh4P92FfSozQN341HRAU-W7q0QjcyODTk',
    appId: '1:660782661242:android:4d348201e46e36bc1085c3',
    messagingSenderId: '660782661242',
    projectId: 'task2-77e20',
    storageBucket: 'task2-77e20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARF9dWZ0iJVKTtBOupzVVGMwokl3K_ROs',
    appId: '1:660782661242:ios:0ef918eaa92ec0901085c3',
    messagingSenderId: '660782661242',
    projectId: 'task2-77e20',
    storageBucket: 'task2-77e20.firebasestorage.app',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARF9dWZ0iJVKTtBOupzVVGMwokl3K_ROs',
    appId: '1:660782661242:ios:0ef918eaa92ec0901085c3',
    messagingSenderId: '660782661242',
    projectId: 'task2-77e20',
    storageBucket: 'task2-77e20.firebasestorage.app',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWYr487z_VMAh_5KR3DDeq5S0ZNHXNGxo',
    appId: '1:660782661242:web:53205decc1eae3181085c3',
    messagingSenderId: '660782661242',
    projectId: 'task2-77e20',
    authDomain: 'task2-77e20.firebaseapp.com',
    storageBucket: 'task2-77e20.firebasestorage.app',
    measurementId: 'G-PHPRCK3814',
  );
}
